In [107]:
'''from google.colab import drive
drive.mount('/content/drive')'''

"from google.colab import drive\ndrive.mount('/content/drive')"

In [108]:
'''cd drive/MyDrive/RoboA/'''

'cd drive/MyDrive/RoboA/'

# Markowitz Efficient Frontier

## 1. Imports

In [109]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import statistics
from tqdm import tqdm
from collections import defaultdict
import math
from itertools import combinations
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential # type: ignore
from tensorflow.keras.layers import LSTM, Dense, Dropout # type: ignore

from fetchData import fetch_raw_data_yf, getSNP500, fetch_raw_data_yf_all, getNasdaq_comp
from MonteCarloRBA import MonteCarloRBA
from PortfolioFunction import maximize_sharpe, create_correlation_matrix, get_sharpe_ratio, get_matrices
from LearningRBA import find_best_asset_to_remove, find_asset_to_add


## 2. Fetch Data

### Get all Nasdaq Stocks

In [110]:
assets= [
    "AAPL",  # Apple Inc.
    "MSFT",  # Microsoft Corporation
    "AMZN",  # Amazon.com Inc.
    "GOOGL", # Alphabet Inc. (Google) Class A
    "GOOG",  # Alphabet Inc. (Google) Class C
    "META",    # Meta Platforms Inc (formerly Facebook)
    "TSLA",  # Tesla Inc
    "UA", # Berkshire Hathaway Inc. Class B
    "JPM",   # JPMorgan Chase & Co.
    "V",     # Visa Inc.
    "JNJ",   # Johnson & Johnson
    "WMT",   # Walmart Inc.
    "PG",    # Procter & Gamble Co.
    "UNH",   # UnitedHealth Group Inc.
    "MA",    # Mastercard Inc.
    "NVDA",  # NVIDIA Corporation
    "HD",    # Home Depot Inc.
    "BAC",   # Bank of America Corp
    "DIS",   # Walt Disney Co
    "PYPL",  # PayPal Holdings
    "VZ",    # Verizon Communications Inc.
    "ADBE",  # Adobe Inc.
    "CMCSA", # Comcast Corporation
    "NFLX",  # Netflix Inc.
    "KO",    # Coca-Cola Co
    "NKE",   # NIKE Inc.
    "PFE",   # Pfizer Inc.
    "MRK",   # Merck & Co., Inc.
    "PEP",   # PepsiCo, Inc.
    "T",     # AT&T Inc.
    "ABT",   # Abbott Laboratories
    "CRM",   # Salesforce.com Inc.
    "ORCL",  # Oracle Corporation
    "ABBV",  # AbbVie Inc.
    "CSCO",  # Cisco Systems, Inc.
    "INTC",  # Intel Corporation
    "TMO",   # Thermo Fisher Scientific Inc.
    "XOM",   # Exxon Mobil Corporation
    "ACN",   # Accenture plc
    "LLY",   # Eli Lilly and Company
    "COST",  # Costco Wholesale Corporation
    "MCD",   # McDonald's Corp
    "DHR",   # Danaher Corporation
    "MDT",   # Medtronic plc
    "NEE",   # NextEra Energy, Inc.
    "BMY",   # Bristol-Myers Squibb Company
    "QCOM",  # Qualcomm Inc
    "CVX",   # Chevron Corporation
    "WFC",   # Wells Fargo & Co
    "LMT",    # Lockheed Martin Corporation
    "GS",   # Goldman Sachs Group, Inc.
    "MS",   # Morgan Stanley
    "IBM",  # International Business Machines Corporation
    "GE",   # General Electric Company
    "F",    # Ford Motor Company
    "GM",   # General Motors Company
    "UBER", # Uber Technologies, Inc.
    "LYFT", # Lyft, Inc.
    "SNAP", # Snap Inc.
    "TWTR", # Twitter, Inc.
    "SPOT", # Spotify Technology S.A.
    "AMD",  # Advanced Micro Devices, Inc.
    "TXN",  # Texas Instruments Incorporated
    "BABA", # Alibaba Group Holding Limited
    "SAP",  # SAP SE
    "HON",  # Honeywell International Inc.
    "BA",   # Boeing Company
    "RTX",  # Raytheon Technologies Corporation
    "CAT",  # Caterpillar Inc.
    "DE",   # Deere & Company
    "MMM",  # 3M Company
    "DUK",  # Duke Energy Corporation
    "SO",   # Southern Company
    "EXC",  # Exelon Corporation
    "NEE",  # NextEra Energy, Inc.
    "AEP",  # American Electric Power Company, Inc.
    "SRE",  # Sempra Energy
    "ETN",  # Eaton Corporation plc
    "EMR",  # Emerson Electric Co.
    "SYY",  # Sysco Corporation
    "KR",   # Kroger Co.
    "GIS",  # General Mills, Inc.
    "K",    # Kellogg Company
    "CPB",  # Campbell Soup Company
    "MO",   # Altria Group, Inc.
    "PM",   # Philip Morris International Inc.
    "BTI",  # British American Tobacco plc
    "RDY",  # Dr. Reddy's Laboratories Ltd.
    "GILD", # Gilead Sciences, Inc.
    "BIIB", # Biogen Inc.
    "CELG", # Celgene Corporation
    "AMGN", # Amgen Inc.
    "SYK",  # Stryker Corporation
    "BSX",  # Boston Scientific Corporation
    "ISRG", # Intuitive Surgical, Inc.
    "ZBH",  # Zimmer Biomet Holdings, Inc.
    "EW",   # Edwards Lifesciences Corporation
    "RMD",  # ResMed Inc.
    "VRTX", # Vertex Pharmaceuticals Incorporated
    "REGN",  # Regeneron Pharmaceuticals, Inc.
]

#assets = getSNP500()

In [111]:
start_date = "2020-01-01"
end_date = "2022-01-01"
raw_data, asset_errors, max_combination= fetch_raw_data_yf_all(assets, start_date, end_date)

[*********************100%***********************]  99 of 99 completed

2 Failed downloads:
['CELG', 'TWTR']: YFTzMissingError('possibly delisted; no timezone found')


Omitted assets ( 2 ):  ['CELG', 'TWTR']
Time to fetch data: 3.50 seconds


### Split into test and train

In [112]:
split = len(raw_data.index) // 2

raw_data_train = raw_data.iloc[:split]
raw_data_test = raw_data.iloc[split:]

## 3. Mean, Volatility and Covariance

In [113]:
names, annualized_returns, cov, correlation_matrix = get_matrices(raw_data_train)

In [114]:
volatility = np.sqrt(np.diag(cov))

risk_free_rate=0
sharpe_ratios = (annualized_returns - risk_free_rate) / volatility

In [115]:
hover_texts = [
    f"{ticker} <br>Volatility: {vol:.3f} <br>Returns: {ret:.3%} <br>Sharpe Ratio: {sr:.3f}"
    for ticker, vol, ret, sr in zip(names, volatility, annualized_returns, sharpe_ratios)
]

fig = go.Figure(data=go.Scatter(
    x=volatility,
    y=annualized_returns,
    mode='markers',
    hoverinfo='text',
    hovertext=hover_texts,
    marker=dict(color=sharpe_ratios, colorscale = 'RdBu', size=6, line=dict(width=1), colorbar=dict(title="Sharpe<br>Ratio")
    )
))

fig.update_layout(
    title='Markowitz Mean Varience Model',
    xaxis_title='Volatility (Standard Deviation)',
    yaxis_title='Annualized Returns',
)

fig.show()

## 4.0 Monte Carlo Method

In [116]:
all_portfolios, dominant_portfolios = MonteCarloRBA(names, cov, annualized_returns, 1000)

100%|██████████| 1000/1000 [00:02<00:00, 474.02it/s]


In [117]:
print (len(dominant_portfolios) ,len(all_portfolios))

61 1000


In [118]:
fig1 = go.Figure()

fig1.add_trace(go.Scatter(
    x=[np.sqrt(p["variance"]) for p in all_portfolios],
    y=[p["return"] for p in all_portfolios],
    mode='markers',
    marker=dict(
        color=[p["sharpe"] for p in all_portfolios],
        showscale=True,
        size=7,
        line=dict(width=1),
        colorscale="RdBu",
        colorbar=dict(title="Sharpe<br>Ratio")
    ),
    hoverinfo='text',
    text=[
        f"Return: {p['return']:.3%}<br>Volatility: {np.sqrt(p['variance']):.3f}<br>" +
        f"Sharpe Ratio: {p['return'] / (np.sqrt(p['variance'])):.3f}<br>" +
        "<br>".join([f"{p['tickers'][i]}: Weight={p['weights'][i]:.3f}" for i in range(len(p['tickers']))])
        for p in all_portfolios
    ]
))

fig1.update_layout(
    xaxis=dict(title='Volatility (Standard Deviation)'),
    yaxis=dict(title='Annualised Returns'),
    title='Sample of Random Portfolios'
)

fig1.show()

In [119]:
fig2 = go.Figure()

fig2.add_trace(go.Scatter(
    x=[np.sqrt(p["variance"]) for p in dominant_portfolios],  # Convert variance to volatility
    y=[p["return"] for p in dominant_portfolios],
    mode='markers',
    marker=dict(
        color=[p["return"] / (np.sqrt(p["variance"])) for p in dominant_portfolios],  # Sharpe Ratio
        showscale=True,
        size=7,
        line=dict(width=1),
        colorscale="RdBu",
        colorbar=dict(title="Sharpe<br>Ratio")
    ),
    hoverinfo='text',
    text=[
        f"Return: {p['return']:.3%}<br>Volatility: {np.sqrt(p['variance']):.3f}<br>" +
        f"Sharpe Ratio: {p['sharpe']:.3f}<br>" +
        "<br>".join([f"{p['tickers'][i]}: Weight={p['weights'][i]:.3f}" for i in range(len(p['tickers']))])
        for p in dominant_portfolios
    ],
    name="Portfolios"
))

fig2.add_trace(go.Scatter(
    x=volatility,
    y=annualized_returns,
    mode='markers',
    hoverinfo='text',
    hovertext=[
        f"{name} <br>Volatility: {vol:.3f} <br>Returns: {ret:.3%} <br>Sharpe Ratio: {sr:.3f}"
        for name, vol, ret, sr in zip(names, volatility, annualized_returns, sharpe_ratios)
    ],
    marker=dict(
        color='brown',
        size=5,
        symbol='triangle-up',  # Sets the marker shape to a triangle
        line=dict(width=1)
    ),
    name="Individual Assets"
))

fig2.update_layout(
    title='Sample of Random Portfolios',
    xaxis_title='Volatility (Standard Deviation)',
    yaxis_title='Annualized Return',
    legend=dict(y=5
    )
)

fig2.show()

## 5.0 Machine Learning Method

### 5.1 Optimization Function Only

In [120]:
def MLRBA_V1(ticker, covariances, returns, num_iterations=None, risk_free_rate = 0, 
             return_power = 1, std_power = 1, return_weight=1/3, corr_weight=1/3, vol_weight= 1/3, num_assets = 8):
    
    if num_iterations is None:
        num_iterations = min(math.comb(len(ticker), num_assets), 100000)
        
    base_portfolio = np.random.choice(list(ticker), num_assets, replace=False)
    #base_portfolio = list(ticker)[:num_assets]
    highest_weighted_sharpe = -np.inf

    all_portfolios = []

    tested_assets = set()
    best_iteration = 0

    def _get_portfolio_stats (portfolio_assets, risk_free_rate = 0):
        p_asset_ret = returns.loc[portfolio_assets].values
        p_asset_var = covariances.loc[portfolio_assets, portfolio_assets].values
        best_p_weights = maximize_sharpe(p_asset_ret, p_asset_var)
        p_ret = np.dot(best_p_weights,p_asset_ret)
        p_var = np.dot(best_p_weights, p_asset_var @ best_p_weights)
        sharpe = get_sharpe_ratio(p_ret, p_var, risk_free_rate, return_power, std_power)

        return p_asset_ret, p_asset_var, sharpe, p_ret, p_var, best_p_weights

    def _update_portfolios_array(portfolios, assets, weights, p_ret, p_var):
        portfolios.append({
            "tickers": assets,
            "weights": weights,
            "return": p_ret,
            "variance": p_var,
            "sharpe": (p_ret-risk_free_rate)/np.sqrt(p_var),
        })

    curr_ret, curr_var, curr_weighted_sharpe, curr_p_return, curr_p_variance, curr_p_weights = _get_portfolio_stats(base_portfolio, risk_free_rate)
    _update_portfolios_array(all_portfolios, base_portfolio, curr_p_weights, curr_p_return, curr_p_variance)

    good_portfolios = all_portfolios.copy()
    best_portfolio = base_portfolio.copy()

    highest_weighted_sharpe = curr_weighted_sharpe
    for i in tqdm(range(num_iterations)):
        asset_to_remove = find_best_asset_to_remove(best_portfolio, curr_var, curr_ret)     #most_correlated_asset, _, _ = find_correlation_matrix(portfolio, curr_variances)
        new_portfolio = [str(asset) for asset in best_portfolio if asset != asset_to_remove]

        ranked_assets = find_asset_to_add(new_portfolio, ticker, covariances, returns, return_weight, corr_weight, vol_weight)         # Find the next best asset to add to the portfolio
        asset_to_add = ranked_assets.index[0]

        for asset in ranked_assets.index:
            if asset not in tested_assets:
                asset_to_add = asset
                break

        new_portfolio.append(asset_to_add)
        tested_assets.add(asset_to_add)

        if len(tested_assets) >= len(ticker) - num_assets:
            print("All assets have been tested")
            break

        # Substitute in and measure portfolio performance based on sharpe ratio
        new_returns, new_var, new_weighted_sharpe, new_p_return, new_p_variance, new_p_weights = _get_portfolio_stats(new_portfolio, risk_free_rate)

        _update_portfolios_array(all_portfolios, new_portfolio, new_p_weights, new_p_return, new_p_variance)

        if new_weighted_sharpe > highest_weighted_sharpe:
            highest_weighted_sharpe = new_weighted_sharpe
            best_portfolio = new_portfolio
            curr_ret, curr_var = new_returns, new_var
            best_iteration = i  # Update the best iteration

            _update_portfolios_array(good_portfolios, new_portfolio, new_p_weights, new_p_return, new_p_variance)

            tested_assets.clear()

        # If Sharpe ratio was worse, then move on to the next least correlated asset
        # If Sharpe ratio is better, set as new base portfolio, and repeat the process for num_iterations times
        # Adjust the sharpe ratio, maybe more emphasis on returns/volatility
        # Update weights to value return or corr
        # See how many iterations it takes to get here, whats a good threshold/stopping point
        # Backtesting
        # Train a model to maybe predict the sharpe ratio of a portfolio

    base_details = good_portfolios[0]
    best_details = good_portfolios[-1]

    return base_details, best_details, good_portfolios, all_portfolios, best_iteration  

base_portfolio, best_portfolio, good_portfolios, total_portfolios, best_iteration = MLRBA_V1(names, cov, annualized_returns)
base_portfolio, best_portfolio, len(total_portfolios), best_iteration

  0%|          | 281/100000 [00:02<11:53, 139.74it/s]

All assets have been tested


({'tickers': array(['JPM_Close', 'AMGN_Close', 'SNAP_Close', 'SAP_Close', 'MSFT_Close',
         'NVDA_Close', 'KO_Close', 'ETN_Close'], dtype='<U11'),
  'weights': array([0.00000000e+00, 1.82560029e-16, 4.93167789e-01, 0.00000000e+00,
         9.11328272e-17, 5.06832211e-01, 0.00000000e+00, 0.00000000e+00]),
  'return': np.float64(0.9342662036157129),
  'variance': np.float64(0.31996445225009845),
  'sharpe': np.float64(1.6516566611323205)},
 {'tickers': ['AMGN_Close',
   'SNAP_Close',
   'KO_Close',
   'TSLA_Close',
   'SPOT_Close',
   'UBER_Close',
   'AMZN_Close',
   'RDY_Close'],
  'weights': array([7.91179403e-17, 1.03345741e-01, 1.34270120e-16, 3.67509627e-01,
         1.31944803e-01, 3.81561688e-16, 3.48873586e-02, 3.62312471e-01]),
  'return': np.float64(1.205945225381083),
  'variance': np.float64(0.2276271557289407),
  'sharpe': np.float64(2.5276419033003377)},
 282,
 192)

In [121]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=[p["variance"]**0.5 for p in total_portfolios],  # Convert variance to volatility
    y=[p["return"] for p in total_portfolios],
    mode='markers',
    marker=dict(
        color=[p["sharpe"] for p in total_portfolios],  # Sharpe Ratio
        showscale=True,
        size=7,
        line=dict(width=1),
        colorscale="RdBu",
        colorbar=dict(title="Sharpe<br>Ratio")
    ),
    hoverinfo='text',
    text=[
        f"Return: {p['return']:.3%}<br>Volatility: {p['variance']**0.5:.3f}<br>" +
        f"Sharpe Ratio: {p['return'] / (p['variance']**0.5):.3f}<br>" +
        "<br>".join([f"{p['tickers'][i]}: Weight={p['weights'][i]:.3f}" for i in range(len(p['tickers']))])
        for p in total_portfolios
    ],
    name="Portfolios"
))

fig.add_trace(go.Scatter(
    x=volatility,
    y=annualized_returns,
    mode='markers',
    hoverinfo='text',
    hovertext=[
        f"{name} <br>Volatility: {vol:.3f} <br>Returns: {ret:.3%} <br>Sharpe Ratio: {sr:.3f}"
        for name, vol, ret, sr in zip(names, volatility, annualized_returns, sharpe_ratios)
    ],
    marker=dict(
        color='brown',
        size=5,
        symbol='triangle-up',  # Sets the marker shape to a triangle
        line=dict(width=1)
    ),
    name="Individual Assets"
))

fig.update_layout(
    title='Sample of Random Portfolios',
    xaxis_title='Volatility (Standard Deviation)',
    yaxis_title='Annualized Return',
    legend=dict(y=5
    )
)


fig.show()

In [122]:
sharpe_ratios = [portfolio['sharpe'] for portfolio in total_portfolios]

fig = go.Figure(data=go.Scatter(x=list(range(len(sharpe_ratios))), y=sharpe_ratios, mode='lines+markers'))
fig.update_layout(title='Sharpe Ratio Over Iterations',
                  xaxis_title='Iteration',
                  yaxis_title='Sharpe Ratio',
                  )
fig.show()

### 5.2 Reinforcement Weight Training

In [123]:
def MLRBA_V2(ticker, covariances, returns, num_iterations=None, risk_free_rate = 0, 
             return_power = 1, std_power = 1, return_weight=1/3, corr_weight=1/3, vol_weight= 1/3, num_assets = 8):
    
    if num_iterations is None:
        num_iterations = min(math.comb(len(ticker), num_assets), 100000)

    base_portfolio = np.random.choice(list(ticker), num_assets, replace=False)
    #base_portfolio = list(ticker)[:num_assets]
    highest_weighted_sharpe = -np.inf
    all_portfolios = []
    tested_assets = set()
    best_iteration = 0

    learning_rate = 0.05

    def _get_portfolio_stats(portfolio_assets, risk_free_rate=0):
        p_asset_ret = returns.loc[portfolio_assets].values
        p_asset_var = covariances.loc[portfolio_assets, portfolio_assets].values
        best_p_weights = maximize_sharpe(p_asset_ret, p_asset_var)
        p_ret = np.dot(best_p_weights, p_asset_ret)
        p_var = np.dot(best_p_weights, p_asset_var @ best_p_weights)
        sharpe = get_sharpe_ratio(p_ret, p_var, risk_free_rate, return_power, std_power)
        return p_asset_ret, p_asset_var, sharpe, p_ret, p_var, best_p_weights

    def _update_portfolios_array(portfolios, assets, weights, p_ret, p_var):
        portfolios.append({
            "tickers": assets,
            "weights": weights,
            "return": p_ret,
            "variance": p_var,
            "sharpe": (p_ret - risk_free_rate) / np.sqrt(p_var),
        })

    curr_ret, curr_var, curr_weighted_sharpe, curr_p_return, curr_p_variance, curr_p_weights = _get_portfolio_stats(base_portfolio, risk_free_rate)
    _update_portfolios_array(all_portfolios, base_portfolio, curr_p_weights, curr_p_return, curr_p_variance)

    good_portfolios = all_portfolios.copy()
    best_portfolio = base_portfolio.copy()
    highest_weighted_sharpe = curr_weighted_sharpe

    improvement_threshold = 0.001

    for i in tqdm(range(num_iterations)):
        asset_to_remove = find_best_asset_to_remove(best_portfolio, curr_var, curr_ret)
        new_portfolio = [str(asset) for asset in best_portfolio if asset != asset_to_remove]

        ranked_assets = find_asset_to_add(new_portfolio, ticker, covariances, returns, return_weight, corr_weight, vol_weight)
        asset_to_add = ranked_assets.index[0]

        for asset in ranked_assets.index:
            if asset not in tested_assets:
                asset_to_add = asset
                break

        new_portfolio.append(asset_to_add)
        tested_assets.add(asset_to_add)

        if len(tested_assets) >= len(ticker) - num_assets:
            print("All assets have been tested")
            break

        new_returns, new_var, new_weighted_sharpe, new_p_return, new_p_variance, new_p_weights = _get_portfolio_stats(new_portfolio, risk_free_rate)
        _update_portfolios_array(all_portfolios, new_portfolio, new_p_weights, new_p_return, new_p_variance)

        if new_weighted_sharpe > highest_weighted_sharpe:
            improvement = new_weighted_sharpe - highest_weighted_sharpe
            highest_weighted_sharpe = new_weighted_sharpe
            best_portfolio = new_portfolio
            curr_ret, curr_var = new_returns, new_var
            best_iteration = i

            asset_return = returns.loc[asset_to_add]
            asset_vol = np.sqrt(covariances.loc[asset_to_add, asset_to_add])
            avg_return = returns.mean()
            avg_vol = np.sqrt(np.diag(covariances)).mean()

            corr_with_portfolio = correlation_matrix.loc[new_portfolio, asset_to_add].drop(asset_to_add).mean()
            avg_corr_in_portfolio = correlation_matrix.loc[new_portfolio].drop(asset_to_add, axis=1).mean().mean()
            
            # Update weights using the current learning rate
            if asset_return > avg_return:
                return_weight += learning_rate * (asset_return - avg_return) / avg_return
            else:
                return_weight -= learning_rate * (avg_return - asset_return) / avg_return

            if asset_vol < avg_vol:
                vol_weight -= learning_rate * (avg_vol - asset_vol) / avg_vol
            else:
                vol_weight += learning_rate * (asset_vol - avg_vol) / avg_vol

            if corr_with_portfolio < avg_corr_in_portfolio:
                corr_weight += learning_rate * (avg_corr_in_portfolio - corr_with_portfolio) / avg_corr_in_portfolio
            else:
                corr_weight -= learning_rate * (corr_with_portfolio - avg_corr_in_portfolio) / avg_corr_in_portfolio

            total = return_weight + corr_weight + vol_weight
            return_weight /= total
            corr_weight /= total
            vol_weight /= total

            if improvement < improvement_threshold:
                learning_rate *= 0.95
            else:
                learning_rate *= 1.01

            _update_portfolios_array(good_portfolios, new_portfolio, new_p_weights, new_p_return, new_p_variance)
            tested_assets.clear()

    base_details = good_portfolios[0]
    best_details = good_portfolios[-1]

    print("Final Weights:", return_weight, corr_weight, vol_weight)
    
    return base_details, best_details, good_portfolios, all_portfolios, best_iteration


base_portfolio, best_portfolio, good_portfolios, total_portfolios, best_iteration = MLRBA_V2(names, cov, annualized_returns)
best_portfolio, best_portfolio['sharpe'], best_iteration

  0%|          | 185/100000 [00:01<15:59, 103.99it/s]

All assets have been tested
Final Weights: 0.9479900276083781 0.027742831163858225 0.02426714122776374


({'tickers': ['COST_Close',
   'BMY_Close',
   'TSLA_Close',
   'SNAP_Close',
   'SPOT_Close',
   'RDY_Close',
   'KR_Close',
   'AMZN_Close'],
  'weights': array([0.00000000e+00, 2.27146734e-16, 3.52911858e-01, 1.01383089e-01,
         1.24328455e-01, 3.43340112e-01, 5.95010159e-02, 1.85354700e-02]),
  'return': np.float64(1.1547453063063942),
  'variance': np.float64(0.208376020177631),
  'sharpe': np.float64(2.529661063227759)},
 np.float64(2.529661063227759),
 96)

In [124]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=[p["variance"]**0.5 for p in total_portfolios],  # Convert variance to volatility
    y=[p["return"] for p in total_portfolios],
    mode='markers',
    marker=dict(
        color=[p["sharpe"] for p in total_portfolios],  # Sharpe Ratio
        showscale=True,
        size=7,
        line=dict(width=1),
        colorscale="RdBu",
        colorbar=dict(title="Sharpe<br>Ratio")
    ),
    hoverinfo='text',
    text=[
        f"Return: {p['return']:.3%}<br>Volatility: {p['variance']**0.5:.3f}<br>" +
        f"Sharpe Ratio: {p['return'] / (p['variance']**0.5):.3f}<br>" +
        "<br>".join([f"{p['tickers'][i]}: Weight={p['weights'][i]:.3f}" for i in range(len(p['tickers']))])
        for p in total_portfolios
    ],
    name="Portfolios"
))

fig.add_trace(go.Scatter(
    x=volatility,
    y=annualized_returns,
    mode='markers',
    hoverinfo='text',
    hovertext=[
        f"{name} <br>Volatility: {vol:.3f} <br>Returns: {ret:.3%} <br>Sharpe Ratio: {sr:.3f}"
        for name, vol, ret, sr in zip(names, volatility, annualized_returns, sharpe_ratios)
    ],
    marker=dict(
        color='brown',
        size=5,
        symbol='triangle-up',  # Sets the marker shape to a triangle
        line=dict(width=1)
    ),
    name="Individual Assets"
))

fig.update_layout(
    title='Sample of Random Portfolios',
    xaxis_title='Volatility (Standard Deviation)',
    yaxis_title='Annualized Return',
    legend=dict(y=5
    )
)


fig.show()

In [125]:
sharpe_ratios = [portfolio['sharpe'] for portfolio in total_portfolios]

fig = go.Figure(data=go.Scatter(x=list(range(len(sharpe_ratios))), y=sharpe_ratios, mode='lines+markers'))
fig.update_layout(title='Sharpe Ratio Over Iterations',
                  xaxis_title='Iteration',
                  yaxis_title='Sharpe Ratio',
                  )
fig.show()

In [126]:
def run_MLRBA_multiple_times(names, cov, annualized_returns, num_runs, version):
    total_good_portfolios_length = 0
    best_portfolios = []
    best_iterations = []

    for i in range(num_runs):
        if version == 'v1':
            _, best_portfolio, good_portfolios, _, best_iteration = MLRBA_V1(names, cov, annualized_returns)
        elif version == 'v2':
            _, best_portfolio, good_portfolios, _, best_iteration = MLRBA_V2(names, cov, annualized_returns)
        
        total_good_portfolios_length += len(good_portfolios)
        best_portfolios.append(best_portfolio)
        best_iterations.append(best_iteration)

    average_length = total_good_portfolios_length / num_runs
    average_iteration = statistics.fmean(best_iterations)
    std_dev_iteration = statistics.stdev(best_iterations) if num_runs > 1 else 0

    return average_length, best_portfolios, average_iteration, std_dev_iteration, best_iterations

num_runs = 1
average_good_portfolios_length_V1, _, average_iteration_V1, std_dev_V1, best_iterations_v1 = run_MLRBA_multiple_times(names, cov, annualized_returns, num_runs, 'v1')
print("Average length of good portfolios:", average_good_portfolios_length_V1, "Average iterations:", average_iteration_V1, "Std Dev:", std_dev_V1)

average_good_portfolios_length_V2, _, average_iteration_V2, std_dev_V2, best_iterations_v2 = run_MLRBA_multiple_times(names, cov, annualized_returns, num_runs, 'v2')
print("Average length of good portfolios:", average_good_portfolios_length_V2, "Average iterations:", average_iteration_V2, "Std Dev:", std_dev_V2)

  0%|          | 396/100000 [00:03<13:02, 127.22it/s]


All assets have been tested
Average length of good portfolios: 26.0 Average iterations: 307.0 Std Dev: 0


  0%|          | 184/100000 [00:01<14:50, 112.14it/s]

All assets have been tested
Final Weights: 0.8705475889959583 0.06673107567260751 0.06272133533143402
Average length of good portfolios: 11.0 Average iterations: 95.0 Std Dev: 0


In [127]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=[
        "Iterations to Reach Best Portfolio (Line Plot)",
        "Iterations to Reach Best Portfolio (Bar Plot)"
    ],)

fig.add_trace(
    go.Scatter(x=list(range(1, num_runs + 1)), y=best_iterations_v1, mode='lines', name='MLRBA V1'),
    row=1, col=1
)
fig.add_trace(
    go.Scatter(x=list(range(1, num_runs + 1)), y=best_iterations_v2, mode='lines', name='MLRBA V2'),
    row=1, col=1
)
fig.update_xaxes(title_text='Run Number', row=1, col=1)
fig.update_yaxes(title_text='Average Number of Iterations to Best Portfolio', row=1, col=1)

fig.add_trace(
    go.Bar(x=['MLRBA V1'], y=[average_iteration_V1], name='MLRBA V1', width=0.4,
           error_y=dict(type='data', array=[std_dev_V1], visible=True)),
    row=1, col=2
)
fig.add_trace(
    go.Bar(x=['MLRBA V2'], y=[average_iteration_V2], name='MLRBA V2', width=0.4,
           error_y=dict(type='data', array=[std_dev_V2], visible=True)),
    row=1, col=2
)
fig.update_xaxes(title_text='Run Number', row=1, col=2)
fig.update_yaxes(title_text='Average Number of Iterations to Best Portfolio', row=1, col=2)

fig.show()

## 6.0 Portfolio Prediction using LSTM

In [161]:
class PortfolioPredictor:
    def __init__(self, raw_data_train, raw_data_test, best_portfolio, n_steps=3, epochs=50, batch_size=32):
        self.raw_data_train = raw_data_train
        self.raw_data_test = raw_data_test
        self.best_portfolio = best_portfolio
        self.n_steps = n_steps
        self.epochs = epochs
        self.batch_size = batch_size
        self.model = None
        self.history = None

    def preprocess_data(self):
        # Selecting data for the tickers
        best_portfolio_data_train = self.raw_data_train[self.best_portfolio['tickers']]
        best_portfolio_data_test = self.raw_data_test[self.best_portfolio['tickers']]
        weights = np.array(self.best_portfolio['weights'])

        # Scaling the data
        scaler = MinMaxScaler(feature_range=(0, 1))
        normalized_train_data = scaler.fit_transform(best_portfolio_data_train)
        normalized_test_data = scaler.transform(best_portfolio_data_test)

        # Calculating weighted returns
        self.weighted_returns_train = np.dot(normalized_train_data, weights)
        self.weighted_returns_test = np.dot(normalized_test_data, weights)

    def create_datasets(self, data):
        X, y = [], []
        for i in range(self.n_steps, len(data)):
            X.append(data[i - self.n_steps:i, :])
            y.append(data[i, :])
        return np.array(X), np.array(y)

    def build_model(self):
        self.model = Sequential([
            LSTM(50, activation='relu', return_sequences=True),
            Dropout(0.2),
            LSTM(50, activation='relu', return_sequences=False),
            Dropout(0.2),
            Dense(1),
        ])

        def tf_weighted_mse(y_true, y_pred, power=3):
            n = tf.shape(y_true)[0]
            normalized_index = tf.cond(
                tf.equal(n, 1),
                lambda: tf.ones([n], dtype=tf.float32),
                lambda: tf.cast(tf.range(n), tf.float32) / tf.cast(n - 1, tf.float32)
            )
            weights = tf.pow(normalized_index, power)
            weights += 1e-6
            weights /= tf.reduce_sum(weights)
            
            squared_errors = tf.square(y_true - y_pred)
            weighted_squared_errors = weights * squared_errors
            return tf.reduce_mean(weighted_squared_errors)

        self.model.compile(optimizer='adam', loss=tf_weighted_mse)

    def train_model(self):
        X_train_weighted, y_train_weighted = self.create_datasets(self.weighted_returns_train.reshape(-1, 1))
        self.history = self.model.fit(X_train_weighted, y_train_weighted, epochs=self.epochs, batch_size=self.batch_size, validation_split=0.1, verbose=0)

    def predict(self, predict_days=None):
        # Generate test set data
        X_test_weighted, y_test_weighted = self.create_datasets(self.weighted_returns_test.reshape(-1, 1))
        
        # Determine the number of predictions based on predict_days
        if predict_days is not None:
            # Ensure that predict_days does not exceed the length of X_test_weighted
            predict_days = min(predict_days, len(X_test_weighted))
            # Slice the last 'predict_days' entries for prediction
            X_test_to_predict = X_test_weighted[-predict_days:]
            self.predictions = self.model.predict(X_test_to_predict)
            self.y_test_weighted = y_test_weighted[-predict_days:]
        else:
            self.predictions = self.model.predict(X_test_weighted)
            self.y_test_weighted = y_test_weighted
        
        # Normalize and compute cumulative returns for the predicted period
        return self.predictions
        
    def plot_loss(self):
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=np.arange(1, len(self.history.history['loss'])+1), y=self.history.history['loss'], mode='lines', name='Training Loss'))
        fig.add_trace(go.Scatter(x=np.arange(1, len(self.history.history['val_loss'])+1), y=self.history.history['val_loss'], mode='lines', name='Validation Loss'))
        fig.update_layout(title='Training and Validation Loss Over Epochs',
                          xaxis_title='Epoch',
                          yaxis_title='Loss',
                          legend_title='Type of Loss')
        fig.show()

    def plot_predictions(self):
        normalized_test = self.normalize_cumulative_returns(self.y_test_weighted)
        normalized_predicted = self.normalize_cumulative_returns(self.predictions)

        fig = go.Figure()
        fig.add_trace(go.Scatter(x=self.raw_data_test.index[-len(normalized_test):], y=normalized_test, mode='lines', name='Actual Weighted Returns'))
        fig.add_trace(go.Scatter(x=self.raw_data_test.index[-len(normalized_predicted):], y=normalized_predicted, mode='lines', name='Predicted Weighted Returns'))
        fig.update_layout(title='Actual vs Predicted Weighted Portfolio Returns',
                          xaxis_title='Date',
                          yaxis_title='Weighted Returns',
                          legend_title='Type')
        fig.show()

    def normalize_cumulative_returns(self, data):
        data_series = pd.Series(data.flatten())
        percentage_changes = data_series.pct_change()
        cumulative_returns = (1 + percentage_changes).cumprod()
        start_value = cumulative_returns.iloc[1]
        normalized_returns = (cumulative_returns / start_value) * 100
        return normalized_returns
    


In [162]:
portfolio_predictor = PortfolioPredictor(raw_data_train, raw_data_test, best_portfolio, n_steps=1)

portfolio_predictor.preprocess_data()
portfolio_predictor.build_model()
portfolio_predictor.train_model()
prediction = portfolio_predictor.predict()   
portfolio_predictor.plot_loss()
portfolio_predictor.plot_predictions()

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step


In [ ]:
def evaluate_portfolios_over_time(raw_data, window_size=5, num_windows=None, threshold=0.05, epochs=50):
    split = len(raw_data.index) // 2
    all_good_portfolios = []
    if num_windows is None:
        num_windows = split // window_size
    
    previous_best_portfolio = None 

    for i in range(num_windows):
        curr_split = i * window_size

        loop_raw_data_train = raw_data.iloc[:split + curr_split]
        loop_raw_data_test = raw_data.iloc[split + curr_split:]
        
        loop_names, loop_annualized_returns, loop_cov, _ = get_matrices(loop_raw_data_train)
        
        _, loop_best_portfolio, loop_good_portfolios, _, _ = MLRBA_V2(loop_names, loop_cov, loop_annualized_returns)
        best_sharpe = loop_best_portfolio['sharpe']
        
        close_to_best = []
        for j in range(len(loop_good_portfolios)):
            difference = abs((best_sharpe - loop_good_portfolios[j]['sharpe']) / best_sharpe)
            if difference < threshold:
                close_to_best.append(loop_good_portfolios[j])

        if previous_best_portfolio is not None:
            close_to_best.append(previous_best_portfolio)

        portfolio_results = {}
        for id, portfolio in enumerate(close_to_best):
            portfolio_predictor = PortfolioPredictor(loop_raw_data_train, loop_raw_data_test, portfolio, n_steps=window_size, epochs=epochs)
            portfolio_predictor.preprocess_data()
            portfolio_predictor.build_model()
            portfolio_predictor.train_model()
            prediction = portfolio_predictor.predict(window_size) 
            print(prediction)          

            if window_size == 1:
                actual = portfolio_predictor.y_test_weighted[0]
                percentage_diff = (prediction[0] - actual) / actual
            else:
                percentage_diff = (prediction[window_size-1] - prediction[0]) / prediction[0]
            
            portfolio_results[id] = percentage_diff

        print(portfolio_results)          
        best_id = max(portfolio_results, key=portfolio_results.get)
        predicted_best_portfolio = close_to_best[best_id]

        previous_best_portfolio = predicted_best_portfolio
        
        start_date = loop_raw_data_test.index[0]
        end_date = loop_raw_data_test.index[window_size-1]
        
        all_good_portfolios.append({
            "portfolio": predicted_best_portfolio,
            "start_date": start_date,
            "end_date": end_date
        })
        print(f'Current iteration: {i}, the best portfolio found was portfolio: {best_id}')
    
    return all_good_portfolios

all_good_portfolios = evaluate_portfolios_over_time(raw_data, window_size=2, num_windows=10, threshold=0.05, epochs=50)

  0%|          | 244/100000 [00:01<13:14, 125.60it/s]


All assets have been tested
Final Weights: 0.9467112369041638 0.04934950289480603 0.003939260201030065
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step
[[0.9706278 ]
 [0.97763836]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step
[[0.8169551]
 [0.8216842]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step
[[0.85186166]
 [0.8572143 ]]
{0: array([0.00722273], dtype=float32), 1: array([0.00578868], dtype=float32), 2: array([0.00628343], dtype=float32)}
Current iteration: 0, the best portfolio found was portfolio: 0


  0%|          | 223/100000 [00:01<12:48, 129.88it/s]


All assets have been tested
Final Weights: 0.9354708493066173 0.028802455269891784 0.035726695423491
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step
[[1.0037936]
 [1.0094848]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step
[[1.1428521]
 [1.1499304]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step
[[1.0089262]
 [1.0160905]]
{0: array([0.00566966], dtype=float32), 1: array([0.00619353], dtype=float32), 2: array([0.00710097], dtype=float32)}
Current iteration: 1, the best portfolio found was portfolio: 2


  0%|          | 178/100000 [00:01<13:47, 120.62it/s]


All assets have been tested
Final Weights: 0.8925415302919841 0.026534423659122387 0.08092404604889342
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step
[[1.0745946]
 [1.0813967]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step
[[1.1031882]
 [1.1109362]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step
[[1.1797644]
 [1.1894041]]
{0: array([0.00632991], dtype=float32), 1: array([0.00702329], dtype=float32), 2: array([0.0081709], dtype=float32)}
Current iteration: 2, the best portfolio found was portfolio: 2


  0%|          | 143/100000 [00:01<12:37, 131.90it/s]


All assets have been tested
Final Weights: 0.8885108092784846 0.03239705794063806 0.07909213278087734
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step
[[0.8969886]
 [0.9020252]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step
[[1.0068462]
 [1.0139029]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step
[[1.0392989]
 [1.0494715]]
{0: array([0.00561507], dtype=float32), 1: array([0.00700873], dtype=float32), 2: array([0.00978795], dtype=float32)}
Current iteration: 3, the best portfolio found was portfolio: 2


  0%|          | 196/100000 [00:01<13:14, 125.59it/s]


All assets have been tested
Final Weights: 0.8888959780239892 0.04567835250309263 0.06542566947291807
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step
[[1.1074568]
 [1.1150892]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step
[[1.0161663]
 [1.0225098]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step
[[1.0953611]
 [1.1066921]]
{0: array([0.0068918], dtype=float32), 1: array([0.00624256], dtype=float32), 2: array([0.0103445], dtype=float32)}
Current iteration: 4, the best portfolio found was portfolio: 2


  0%|          | 408/100000 [00:03<14:42, 112.91it/s]


All assets have been tested
Final Weights: 0.9048316681586921 0.056065024612395764 0.039103307228912046
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step
[[1.3022965]
 [1.3157401]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step
[[1.3519233]
 [1.3663193]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step
[[1.0528054]
 [1.0625068]]
{0: array([0.01032299], dtype=float32), 1: array([0.0106485], dtype=float32), 2: array([0.00921478], dtype=float32)}
Current iteration: 5, the best portfolio found was portfolio: 1


  0%|          | 335/100000 [00:02<13:51, 119.93it/s]


All assets have been tested
Final Weights: 0.8722277480145983 0.04727033844056798 0.0805019135448337
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step
[[1.6981015]
 [1.7151324]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step
[[1.5706236]
 [1.5857531]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step
[[1.413464 ]
 [1.4293905]]
{0: array([0.01002934], dtype=float32), 1: array([0.00963276], dtype=float32), 2: array([0.01126778], dtype=float32)}
Current iteration: 6, the best portfolio found was portfolio: 2


  0%|          | 317/100000 [00:02<13:56, 119.16it/s]


All assets have been tested
Final Weights: 0.8904192464942469 0.030480370584783725 0.07910038292096948
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 192ms/step
[[1.218976 ]
 [1.2263942]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step
[[1.2502747]
 [1.2582815]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step
[[1.3910612]
 [1.4062284]]
{0: array([0.00608556], dtype=float32), 1: array([0.00640404], dtype=float32), 2: array([0.01090336], dtype=float32)}
Current iteration: 7, the best portfolio found was portfolio: 2


  0%|          | 386/100000 [00:03<13:52, 119.70it/s]


All assets have been tested
Final Weights: 0.8703816133171932 0.054539389214092085 0.07507899746871473
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step
[[1.4008654]
 [1.4120193]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step
[[1.7514302]
 [1.7686061]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step
[[1.0609052]
 [1.0699317]]
{0: array([0.00796209], dtype=float32), 1: array([0.00980679], dtype=float32), 2: array([0.00850833], dtype=float32)}
Current iteration: 8, the best portfolio found was portfolio: 1


  0%|          | 160/100000 [00:01<13:24, 124.10it/s]


All assets have been tested
Final Weights: 0.9042984592945802 0.0429951413047036 0.05270639940071622
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step
[[1.459542 ]
 [1.4636421]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step
[[1.4701235]
 [1.4850107]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step
[[1.6038978]
 [1.6172978]]
{0: array([0.00280916], dtype=float32), 1: array([0.01012651], dtype=float32), 2: array([0.00835462], dtype=float32)}
Current iteration: 9, the best portfolio found was portfolio: 1


In [158]:
def extract_asset_returns(raw_data, assets, start_date, end_date):
    if not isinstance(raw_data.index, pd.DatetimeIndex):
        raw_data.index = pd.to_datetime(raw_data.index)

    filtered_data = raw_data.loc[start_date:end_date, assets]

    return filtered_data

ML_portfolio = []

for i in range(len(all_good_portfolios)):
    curr_best_portfolio = all_good_portfolios[i]['portfolio']
    best_curr_port_assets = curr_best_portfolio['tickers']

    best_curr_port_assets_test_data = extract_asset_returns(raw_data, best_curr_port_assets, all_good_portfolios[i]['start_date'], all_good_portfolios[i]['end_date'])

    curr_best_portfolio_weights = curr_best_portfolio['weights']

    weighted_returns = best_curr_port_assets_test_data.mul(curr_best_portfolio_weights, axis='columns')
    portfolio_daily_returns = weighted_returns.sum(axis=1)

    ML_portfolio.append(portfolio_daily_returns)

ML_portfolio

[Date
 2020-12-31    136.823524
 2021-01-04    139.090044
 dtype: float64,
 Date
 2021-01-05    140.199127
 2021-01-06    142.613553
 dtype: float64,
 Date
 2021-01-07    152.034521
 2021-01-08    162.323154
 dtype: float64,
 Date
 2021-01-11    153.437026
 2021-01-12    158.392779
 dtype: float64,
 Date
 2021-01-13    158.767832
 2021-01-14    156.672839
 dtype: float64,
 Date
 2021-01-15    162.386602
 2021-01-19    165.247623
 dtype: float64,
 Date
 2021-01-20    167.673521
 2021-01-21    169.272913
 dtype: float64,
 Date
 2021-01-22    168.745175
 2021-01-25    172.802748
 dtype: float64,
 Date
 2021-01-26    181.335058
 2021-01-27    177.284464
 dtype: float64,
 Date
 2021-01-28    161.220423
 2021-01-29    155.226544
 dtype: float64]

In [159]:
import pandas as pd

def chain_portfolio_performance(weekly_series_list, starting_value=100):
    continuous_series = pd.Series()
    current_value = starting_value

    for week_series in weekly_series_list:
        # Normalize the week so that it starts at 1 (or current_value)
        week_normalized = week_series / week_series.iloc[0]
        # Scale the normalized week to start at current_value
        week_scaled = week_normalized * current_value
        # Update the current_value to the last value of this week
        current_value = week_scaled.iloc[-1]
        # Append the week_series to the continuous_series
        continuous_series = pd.concat([continuous_series, week_scaled])
    
    return continuous_series

ML_portfolio_streamed = chain_portfolio_performance(ML_portfolio, starting_value=100)
ML_portfolio_streamed

C:\Users\tongc\AppData\Local\Temp\ipykernel_27484\3348600324.py:15: FutureWarning:

The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.



2020-12-31    100.000000
2021-01-04    101.656528
2021-01-05    101.656528
2021-01-06    103.407197
2021-01-07    103.407197
2021-01-08    110.405073
2021-01-11    110.405073
2021-01-12    113.970968
2021-01-13    113.970968
2021-01-14    112.467084
2021-01-15    112.467084
2021-01-19    114.448594
2021-01-20    114.448594
2021-01-21    115.540288
2021-01-22    115.540288
2021-01-25    118.318520
2021-01-26    118.318520
2021-01-27    115.675565
2021-01-28    115.675565
2021-01-29    111.374960
dtype: float64

In [160]:
ML_daily_returns = ML_portfolio_streamed.pct_change()
ML_cumulative_returns = (1 + ML_daily_returns).cumprod()

ML_cumulative_returns.iloc[0] = 1
ML_portfolio_normalized = (ML_cumulative_returns / ML_cumulative_returns.iloc[0]) * 100

Nasdaq_comp = getNasdaq_comp(ML_portfolio_streamed.index[0], ML_portfolio_streamed.index[-1])

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=Nasdaq_comp.index,
    y=Nasdaq_comp['Normalized'],
    mode='lines',
    name='Nasdaq Composite'
))

fig.add_trace(go.Scatter(
    x=ML_cumulative_returns.index,
    y=ML_portfolio_normalized,
    mode='lines',
    name='Portfolio Growth'
))

fig.update_layout(
    title='Comparison of Portfolio vs. Nasdaq Composite Growth',
    xaxis_title='Date',
    yaxis_title='Normalized Value (Base 100%)',
    xaxis=dict(
        type='date',
        tickformat='%b %Y',
        tickmode='auto'
    )
)

[*********************100%***********************]  1 of 1 completed

Omitted assets: []
Time to fetch data: 0.10 seconds
Max combination of assets with complete data: 1


## 7.0 Find Optimal Portfolio Size

In [56]:
all_portfolios, dominant_portfolios = MonteCarloRBA(names, cov, annualized_returns, 10000, "random", 3, 50)

100%|██████████| 10000/10000 [00:09<00:00, 1018.95it/s]


In [57]:
rd_portfolio_sizes = [len(portfolio['tickers']) for portfolio in all_portfolios]
rd_volatility = [np.sqrt(portfolio['variance']) for portfolio in all_portfolios]
rd_returns = [portfolio['return'] for portfolio in all_portfolios]

volatility_by_size = defaultdict(list)
for size, vol, ret in zip(rd_portfolio_sizes, rd_volatility, rd_returns):
    volatility_by_size[size].append((vol, ret))

average_volatility = {size: np.mean([v[0] for v in vols]) for size, vols in volatility_by_size.items()}
average_returns = {size: np.mean([v[1] for v in vols]) for size, vols in volatility_by_size.items()}

sorted_sizes = sorted(average_volatility.keys())
sorted_average_vols = [average_volatility[size] for size in sorted_sizes]
sorted_average_rets = [average_returns[size] for size in sorted_sizes]

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=sorted_sizes,
    y=sorted_average_vols,
    mode='lines',
    name='Average Volatility'
))
fig.add_trace(go.Scatter(
    x=sorted_sizes,
    y=sorted_average_rets,
    mode='lines',
    name='Average Returns'
))

fig.update_layout(
    title='Average Volatility and Returns by Portfolio Size',
    xaxis_title='Number of Assets in Portfolio',
    yaxis_title='Average Value',
    xaxis=dict(type='category'),
)

fig.show()


## 8.0 Testing Against Others

In [144]:
best_port_assets = best_portfolio['tickers']
best_port_assets_test_data = raw_data_test.loc[:, best_port_assets]

Nasdaq_comp = getNasdaq_comp(best_port_assets_test_data.index[0], best_port_assets_test_data.index[-1])

best_portfolio_weights = best_portfolio['weights']
normalized_prices = best_port_assets_test_data.div(best_port_assets_test_data.iloc[0])
daily_returns = normalized_prices.pct_change()
weighted_returns = daily_returns.mul(best_portfolio_weights, axis='columns')
portfolio_daily_returns = weighted_returns.sum(axis=1)
portfolio_cumulative_returns = (1 + portfolio_daily_returns).cumprod()

portfolio_start = portfolio_cumulative_returns.iloc[0]
portfolio_normalized = (portfolio_cumulative_returns / portfolio_start) * 100

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=Nasdaq_comp.index,
    y=Nasdaq_comp['Normalized'],
    mode='lines',
    name='Nasdaq Composite'
))

fig.add_trace(go.Scatter(
    x=portfolio_cumulative_returns.index,
    y=portfolio_normalized,
    mode='lines',
    name='Portfolio Growth'
))

fig.add_trace(go.Scatter(
    x=ML_cumulative_returns.index,
    y=ML_portfolio_normalized,
    mode='lines',
    name='Portfolio Growth'
))

fig.update_layout(
    title='Comparison of Portfolio vs. Nasdaq Composite Growth',
    xaxis_title='Date',
    yaxis_title='Normalized Value (Base 100)',
    xaxis=dict(
        type='date',
        tickformat='%b %Y',
        tickmode='auto'
    )
)

[*********************100%***********************]  1 of 1 completed

Omitted assets: []
Time to fetch data: 0.02 seconds
Max combination of assets with complete data: 1
